import type { ZoteroVersions } from "./compat.ts";
import type { CensusRow } from "./run.ts";
import { SOURCE_IDS } from "./sources.ts";

interface Meta {
  generatedAt: string;
  zoteroVersions: ZoteroVersions;
  funnel: Record<string, number>;
  queries: { source: string; query: string; repos: number }[];
}

const fmt = (n: number | null | undefined) =>
  n === null || n === undefined ? "–" : n.toLocaleString("en-US");
const pct = (a: number, b: number) => (b ? `${Math.round((100 * a) / b)}%` : "–");

function quantiles(values: number[]): string {
  const v = [...values].sort((a, b) => a - b);
  if (!v.length) return "–";
  const q = (p: number) => v[Math.min(v.length - 1, Math.floor(p * v.length))] ?? 0;
  return `median ${fmt(q(0.5))} · p75 ${fmt(q(0.75))} · p90 ${fmt(q(0.9))} · max ${fmt(v.at(-1))}`;
}

function table(header: string[], rows: (string | number)[][]): string {
  return [
    `| ${header.join(" | ")} |`,
    `|${header.map(() => "---").join("|")}|`,
    ...rows.map((r) => `| ${r.join(" | ")} |`),
  ].join("\n");
}

const supportsCell = (r: CensusRow) => (r.supports.length ? r.supports.join(", ") : "–");
const link = (r: CensusRow) => `[${r.name.replaceAll("|", "/")}](${r.url})`;

export function buildReport(rows: CensusRow[], meta: Meta): string {
  const zv = meta.zoteroVersions;
  const plugins = rows.filter((r) => r.verdict.startsWith("zotero-plugin"));
  const current = zv.currentMajor;
  const out: string[] = [];

  out.push(`# Zotero plugin census, ${meta.generatedAt.slice(0, 10)}`);
  out.push(
    "Generated by `pnpm atlas census`: deterministic, no LLM calls. A repo counts as a Zotero plugin only when a GitHub release ships an `.xpi` whose manifest targets Zotero (read with HTTP range requests). Raw data: `data/census/census.csv` (one row per repo) and `data/census/candidates.csv` (every discovered candidate).",
  );

  out.push("## Funnel");
  const f = meta.funnel;
  out.push(
    table(
      ["Stage", "Repos"],
      [
        ["Candidates nominated by any source", fmt(f.candidates)],
        ["…that still exist on GitHub (renames collapsed)", fmt(f.existing)],
        ["…with an .xpi in one of their last 10 releases", fmt(f.withXpiRelease)],
        ["Checked in detail (xpi releases + every curated-list entry)", fmt(f.selected)],
        ["**Confirmed Zotero plugins (manifest.json, Zotero 7+)**", `**${fmt(f.zoteroPlugins)}**`],
        ["Confirmed legacy plugins (install.rdf, Zotero ≤ 6)", fmt(f.legacyPlugins)],
      ],
    ),
  );

  out.push("## Zotero versions detected");
  out.push(
    `Current major **${current}** (release: ${Object.entries(zv.release)
      .map(([p, v]) => `${p} ${v}`)
      .join(", ")}). ` +
      `Next major: ${zv.nextMajor ?? "none"} (dev: ${Object.values(zv.dev)[0] ?? "–"}). ` +
      `Last stable per older major: ${Object.entries(zv.lastTagPerMajor)
        .filter(([m]) => Number(m) >= 6 && Number(m) < current)
        .map(([m, v]) => `${m} → ${v}`)
        .join(", ")}.`,
  );

  out.push("## Where the plugins were found");
  const bySource = SOURCE_IDS.map((s) => {
    const nominated = meta.queries.filter((q) => q.source === s).reduce((a, q) => a + q.repos, 0);
    const confirmed = plugins.filter((p) => p.sources.includes(s)).length;
    const only = plugins.filter((p) => p.sources.length === 1 && p.sources[0] === s).length;
    return [s, fmt(nominated), fmt(confirmed), fmt(only)];
  });
  out.push(table(["Source", "Nominated", "Confirmed plugins", "Found only here"], bySource));
  const newFinds = plugins.filter((p) => p.newFind);
  out.push(
    `**${newFinds.length} confirmed plugins (${pct(newFinds.length, plugins.length)}) appear in none of the curated lists** (Add-on Market, its tracked list, zotero-chinese, the research sheet, Zotero's archived wiki page).`,
  );

  out.push("## Compatibility (latest release with an .xpi)");
  const majors = [6, 7, 8, 9, 10, 11].filter((m) => m <= (zv.nextMajor ?? current));
  out.push(
    table(
      ["Zotero major", "Plugins whose latest release supports it", "Share"],
      majors.map((m) => {
        const n = plugins.filter((p) => p.supports.includes(m)).length;
        return [
          `${m}${m === current ? " (current)" : m === zv.nextMajor ? " (dev)" : ""}`,
          fmt(n),
          pct(n, plugins.length),
        ];
      }),
    ),
  );

  out.push("## Maintenance (last commit or release)");
  const states = ["active", "slowing", "dormant", "archived", "unknown"] as const;
  out.push(
    table(
      ["Status", "Rule", "Plugins", `…of which work with Zotero ${current}`],
      states.map((s) => {
        const group = plugins.filter((p) => p.maintenance === s);
        const rule = {
          active: "≤ 6 months",
          slowing: "6–18 months",
          dormant: "> 18 months",
          archived: "archived on GitHub",
          unknown: "no dates",
        }[s];
        return [s, rule, fmt(group.length), fmt(group.filter((p) => p.worksWithCurrent).length)];
      }),
    ),
  );

  out.push("## Distributions (confirmed plugins)");
  out.push(
    [
      `- Stars: ${quantiles(plugins.map((p) => p.stars ?? 0))}`,
      `- Lifetime .xpi downloads (GitHub only): ${quantiles(plugins.map((p) => p.totalXpiDownloads ?? 0))}`,
      `- Contributors: ${quantiles(plugins.filter((p) => p.contributors !== null).map((p) => p.contributors as number))}; single-contributor plugins: ${fmt(plugins.filter((p) => p.contributors === 1).length)} (${pct(plugins.filter((p) => p.contributors === 1).length, plugins.length)})`,
      `- Forks listed as plugins: ${fmt(plugins.filter((p) => p.isFork).length)}`,
      `- Total GitHub .xpi downloads across all confirmed plugins: ${fmt(plugins.reduce((s, p) => s + (p.totalXpiDownloads ?? 0), 0))}`,
    ].join("\n"),
  );

  out.push("## Traction");
  const tier = (lo: number, hi: number, f: (r: CensusRow) => number) =>
    plugins.filter((p) => f(p) >= lo && f(p) < hi).length;
  const stars = (r: CensusRow) => r.stars ?? 0;
  const dls = (r: CensusRow) => r.totalXpiDownloads ?? 0;
  out.push(
    table(
      ["Stars", "Plugins", "Downloads", "Plugins"],
      [
        ["100+", fmt(tier(100, Infinity, stars)), "10,000+", fmt(tier(10_000, Infinity, dls))],
        ["10–99", fmt(tier(10, 100, stars)), "1,000–9,999", fmt(tier(1_000, 10_000, dls))],
        ["1–9", fmt(tier(1, 10, stars)), "50–999", fmt(tier(50, 1_000, dls))],
        ["0", fmt(tier(0, 1, stars)), "under 50", fmt(tier(0, 50, dls))],
      ],
    ),
  );

  out.push("## When the plugins were created");
  const years = [...new Set(plugins.map((p) => p.createdAt?.slice(0, 4) ?? "?"))].sort();
  out.push(
    table(
      ["Year created", "All plugins", "With 10+ stars", "Non-fork"],
      years.map((y) => {
        const g = plugins.filter((p) => (p.createdAt?.slice(0, 4) ?? "?") === y);
        return [
          y,
          fmt(g.length),
          fmt(g.filter((p) => stars(p) >= 10).length),
          fmt(g.filter((p) => !p.isFork).length),
        ];
      }),
    ),
  );

  out.push("## Same add-on ID shipped from more than one repo");
  const byId = new Map<string, CensusRow[]>();
  for (const p of plugins) {
    if (p.addonId) byId.set(p.addonId, [...(byId.get(p.addonId) ?? []), p]);
  }
  const shared = [...byId.entries()]
    .filter(([, list]) => list.length > 1)
    .sort((a, b) => b[1].length - a[1].length);
  out.push(
    `${fmt(shared.length)} add-on IDs appear in ${fmt(shared.reduce((s, [, l]) => s + l.length, 0))} repos. Zotero treats every build with the same ID as the same add-on, so installing a fork replaces the original and takes updates from wherever the fork's \`update_url\` points. Most are personal forks or copies of a template that kept its ID, but each is worth a look.`,
  );
  out.push(
    table(
      ["Add-on ID", "Repos", "Forks", "Most-downloaded repo"],
      shared.slice(0, 15).map(([id, list]) => {
        const top = [...list].sort((a, b) => dls(b) - dls(a))[0] as CensusRow;
        return [`\`${id}\``, fmt(list.length), fmt(list.filter((p) => p.isFork).length), top.repo];
      }),
    ),
  );

  const topTable = (list: CensusRow[]) =>
    table(
      ["#", "Plugin", "Stars", "Downloads", "Contrib.", "Last activity", "Zotero", "Status"],
      list.map((r, i) => [
        i + 1,
        link(r),
        fmt(r.stars),
        fmt(r.totalXpiDownloads),
        fmt(r.contributors),
        r.lastActivityAt?.slice(0, 10) ?? "–",
        supportsCell(r),
        r.maintenance,
      ]),
    );

  out.push("## Top 40 by lifetime downloads");
  out.push(
    topTable(
      [...plugins]
        .sort((a, b) => (b.totalXpiDownloads ?? 0) - (a.totalXpiDownloads ?? 0))
        .slice(0, 40),
    ),
  );

  out.push(`## Popular plugins that don't declare Zotero ${current} support`);
  out.push(
    topTable(
      plugins
        .filter((p) => !p.worksWithCurrent && p.verdict === "zotero-plugin")
        .sort((a, b) => (b.totalXpiDownloads ?? 0) - (a.totalXpiDownloads ?? 0))
        .slice(0, 20),
    ),
  );

  out.push("## New finds: confirmed plugins missing from every curated list (top 30 by stars)");
  out.push(topTable(newFinds.slice(0, 30)));

  out.push("## Curated-list entries that are not confirmed plugins");
  const curatedNonPlugins = rows.filter(
    (r) => !r.newFind && !r.verdict.startsWith("zotero-plugin"),
  );
  const byVerdict = new Map<string, CensusRow[]>();
  for (const r of curatedNonPlugins)
    byVerdict.set(r.verdict, [...(byVerdict.get(r.verdict) ?? []), r]);
  out.push(
    table(
      ["Verdict", "Repos", "Examples"],
      [...byVerdict.entries()].map(([v, list]) => [
        v,
        fmt(list.length),
        list
          .slice(0, 4)
          .map((r) => r.repo)
          .join(", "),
      ]),
    ),
  );

  out.push("## Caveats");
  out.push(
    [
      "- **Downloads are a floor.** GitHub counts only direct asset downloads: mirrors (gh-proxy, Gitee), Zotero's own update channel when it points elsewhere, and replaced assets (counts reset) are missed. Auto-updates inflate counts for plugins that update often.",
      "- **Compatibility is what the manifest declares**, judged against real Zotero releases, not tested behaviour. It covers the latest release only; older releases may support older Zotero versions (see `addon_market_targets`).",
      "- **Discovery is GitHub-only.** Plugins hosted solely on Gitee or elsewhere are missed unless a curated list links to a GitHub repo.",
      "- Repos with an .xpi only in releases older than their last 10 are found only if a curated list names them.",
    ].join("\n"),
  );

  return `${out.join("\n\n")}\n`;
}
